DROP TABLE IF EXISTS yoga_poses;

CREATE TABLE yoga_poses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nameEng TEXT NOT NULL,
    alias TEXT,
    nameSan TEXT NOT NULL,
    benefits TEXT,
    level TEXT NOT NULL,
    poseType TEXT NOT NULL,
    img TEXT,
    video TEXT NOT NULL,
)