DROP TABLE IF EXISTS flows;

CREATE TABLE flows (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    author REFERENCES users(id) ON DELETE CASCADE NOT NULL, 
    peakPose REFERENCES yoga_poses(id) ON DELETE SET NULL,
)
-- //on delete i want to delete the flow but NOT AFFECT the yoga-poses table in any way...// when author/user is deleted it removes the flows as well