BEGIN;

INSERT INTO yoga_poses (name_eng, alias, name_san, benefits, pose_level, pose_type, img, video)
VALUES

('Fierce Pose', 'Chair', 'Utkatasana', 'Improves balance, mobility, posture, strengthens legs, glutes and ankles, opens chest and shoulders', 'begginer', 'balancing, standing pose', 'https://www.dropbox.com/s/8quay5307gbpsn4/chair.png?dl=0', 'https://www.youtube.com/embed/Kp7XJkG9ubc' ),
('Half Lord of the Fishes Pose', 'Sitting Half Spinal Twist','Matsyendrasana', 'Strengthens and lengthens the spine, cleanses internal organs, activates digestive tract, opens the chest and heart space', 'intermediate', 'seated, twist', 'https://www.dropbox.com/s/watfq2y9ujum822/matsyendrasana.png?dl=0', 'https://www.youtube.com/embed/OMGUMuUbK4Q' ),
('Revolving Side Angle Pose','', 'Parivrtta Parsvakonasana', 'Improves flexibility, strengthens legs and core, opens the hips, chest, and shoulders, massages internal organs, improves digestion', 'intermediate', 'balancing, twist, standing', 'https://www.dropbox.com/s/1dmh7p0bh7uw7vn/revolving-side-angle.png?dl=0', 'https://www.youtube.com/embed/XRfxkioaG-Q'),
('Side Angle Pose','', 'Parsvakonasana', 'Stretches the inner thighs, groins, and side body, Strengthens the quadriceps and hamstrings, as well as the hips, knees, and ankles, Improves stamina, Relieves low back pain, menstrual pain, and sciatica, Massages the abdominal organs, Opens the chest and shoulders', 'beginner', 'balancing, standing', 'https://www.dropbox.com/s/cy8xcfru0ylr47o/side-angle.png?dl=0', 'https://www.youtube.com/embed/7fFWy2IT9FE'),
('Reversed Tabletop Pose', '', 'Ardha Purvottanasana', 'Opens the heart space, opens the frontline of body, engages the core and quadriceps', 'beginner', 'strengthening, seated, backbend', 'https://www.dropbox.com/s/kq0jn1uptbjvoff/reversed%20tabletop.png?dl=0', 'https://www.youtube.com/embed/nWaOi23tXeA'),
('Cow pose','', 'Bitilasana', 'Strengthens arms, shoulders, and knees, offers space to open your spine, grounds your energy and calms your nervous system', 'beginner',  'core', 'https://www.dropbox.com/s/lvw8xi68rjbo626/cow.png?dl=0', 'https://www.youtube.com/embed/kqnua4rHVVA'),
('Tree pose', '', 'Vrksasana', 'Tones leg muscles, engages core muscles, enhances balancing abilities, aids in the alignment of the spine, lessens stress by improving focus and alertness', 'standing, balancing','beginner', 'https://www.dropbox.com/s/ntz8xlb1h527ws0/tree.png?dl=0', 'https://www.youtube.com/embed/wdln9qWYloU'),
('Warrior 3','', 'Virabhadrasana III', 'Strengthens the entire body, improves balance, improves posture, aids in increasing energy and boosting concentration', 'intermediate', 'standing, balancing', 'https://www.dropbox.com/s/r7br8ne68bv9o7m/war3.png?dl=0', 'https://www.youtube.com/embed/S74efRiLo6k'),
('Warrior 2','', 'Virabhadrasana II', 'Strengthens the entire body, improves mobility in hips', 'beginner',  'standing, balancing', 'https://www.dropbox.com/s/3oyzocuwi2eeyw1/war2.png?dl=0', 'https://www.youtube.com/embed/PZcp3Lz7WJs'),
('Warrior 1', '','Virabhadrasana I', 'Strengthens the entire body, improves mobility in hips, stretches back foot, chest',  'beginner', 'standing, balancing', 'https://www.dropbox.com/s/594wq4aac8xjl13/war1.png?dl=0', 'https://www.youtube.com/embed/4hqmLOpkHrw'),
('Rested Half Pigeon Pose', 'Pigeon', 'Ardha Kapotasana', 'Cleanses the liver, restorative energy, opens the hips deeply, releases stored emotions', 'intermediate', 'forward fold, Hip Opener, Seated', 'https://www.dropbox.com/s/qh7vn26hf7yq5kc/king%20pigeon.png?dl=0', 'https://www.youtube.com/embed/jkJwvzt12dA'),
('Cobra', '', 'Bhujangasana', 'Improves spinal flexibility and mobility, deepens breathing, strengthens shoulders and chest, opens heart space, energizes entire body, Lessens stress ', 'beginner', 'backbend, heart opener', 'https://www.dropbox.com/s/hrzjb6af3tt5b0o/cobra.png?dl=0', 'https://www.youtube.com/embed/ZqnbaBx09-E'),
('Bharadvaja Twist', '','Bharadvajasana', 'Massages the abdominal organs Improves digestion Stretches the spine and shoulders Increases spinal flexibility Relieves stress',  'intermediate', 'Hip Opener,  Seated, Twist', 'https://www.dropbox.com/s/rksfz8gf8h2o1xl/bharadvaja%20twist.png?dl=0', 'https://www.youtube.com/embed/Z43c1aeAMeM'),       
('Boat', '', 'Paripurna Navasana', 'Strengthens the hips flexors, abdominals, and low spine, Focuses the mind, Improves overall core strength, Strengthens the quadriceps, Improves coordination and balance, Stimulates the abdominal organs and improves digestion, Stimulates the kidneys, thyroid, and prostate glands', 'beginner', 'Core, Seated, Strenghening', 'https://www.dropbox.com/s/e1d4g51vmgvquoa/boat.png?dl=0', 'https://www.youtube.com/embed/UHSqdPl2R4Q'),  
('Bound Angle Pose', '', 'Baddha Konasana', 'Lengthens and releases adductor muscles of the groin, Stretches the low back and thighs, Improves external rotation of the hips, Strengthens the hip flexors and abdominals, Stimulates the abdominal organs and digestive system, Relieves symptoms of menstruation and menopause', 'beginner', 'Forward Fold, Hip Opener, Seated',  'https://www.dropbox.com/s/hi6nstyjbq0j3y8/butterfly.png?dl=0', 'https://www.youtube.com/embed/RWvNyJyasiI'),
('Bow pose', '', 'Dhanurasana', 'Lengthens the hip flexors and strengthens the hamstrings, Detoxes the kidneys and adrenal glands, Strengthens the shoulders and spine extensors, Opens the chest and throat', 'intermediate',  'Backbend, Heart Opener', 'https://www.dropbox.com/s/wks6ic8kyqfm051/bow.png?dl=0', 'https://www.youtube.com/embed/4P2mYcOGxbU'),     
('Bridge pose', '', 'Setu Bandha Sarvangasana', 'Stimulates the thyroid, Improves posture and opens rounded shoulders, Stretches the abdominal organs and improves digestion, Tones the female reproductive organs, Relieves anxiety, fatigue, and insomnia', 'beginner','Backbend, Heart Opener', 'https://www.dropbox.com/s/f1kefp2tvmb6w3g/bridge.png?dl=0', 'https://www.youtube.com/embed/JY9TLhKIQdE'),
('Camel pose', '', 'Ustrasana', 'Stretches the vertebrae, Massages the abdominal organs and stimulates digestion, Stretches the neck, chest, abs, hips, and thighs, Stimulates the spinal nerves, Strengthens the back muscles and core, Improves posture, Regulates the thyroid', 'intermediate', 'Backbend, Heart Opener', 'https://www.dropbox.com/s/2wjt66x79ouxbm0/camel.png?dl=0', 'https://www.youtube.com/embed/8q7GxnIFsQo'),
('Cat', '', 'Marjaryasana', 'Strengthens the arms, wrists, and shoulders, Relieves tension in the thoracic, cervical, and lumbar spine; warming up the back for practice, Gently massages the abdominal organs and improves digestion, Strengthens and tones the abdominal muscles, Increases spinal flexibility', 'beginner', 'Backbend, Core', 'https://www.dropbox.com/s/5qkbzcefgwop30h/cat.png?dl=0', 'https://www.youtube.com/embed/Ov65nNSWrfw'),    
('Low lundge with backbend B','', 'Anjaneyasana', 'Strenghens gluteus and quadriceps,opens hips and hip flexors, shoulders, lungs,and chest, improves balance and concentration, relieves sciatica, stimulates digestive and reproductive organs', 'intermediate',
'Backbend, Core, standing, balancing', 'https://www.dropbox.com/s/0sliocqlssxy875/low%20lungeB.jpg?dl=0', 'https://www.youtube.com/embed/oNNVpM8sJvc'),
('Sun salutation A & B', '', 'Surya Namaskar A & B', 'Prepares for practice, warms up the whole body, stretches leg and back muscles, opens the chest, stimulates and energizes ', 'beginner', 'Seated, Forward Bend', 'https://www.dropbox.com/s/zcyzaz9t52ntn5b/suryaB.jpg?dl=0', 'https://www.youtube.com/embed/aWE7XenIWlc'),
('Forearm wheel','', 'Dwi Pada Viparita Dandasana', 'Deep chest and shoulder openner as well as front body, abdominals and hip abductors, strengthens back, sholders, legs and core muscle', 'advanced', 'Backbend, core', 'https://www.youtube.com/embed/kqnua4rHVVA', 'https://www.youtube.com/embed/-5inRni3sQY'),
('Firefly', '','Tittibhasana', 'Challenges and improves balance, tones the internal organs, strengthens the core, arms, wrists,and legs, opens the hips', 'advanced', 'Arm Balance, Forward Bend, Hip Opener', 'https://www.dropbox.com/s/tgxggdkf6ei55h3/firefly%20.png?dl=0', 'https://www.youtube.com/embed/SgxtWOz_2FI'),
('Revolved Goddess Pose','' ,'Parivrtta Utkata Konasana', 'Opens the hips, improves balance, tones the internal organs, strengthens the core', 'intermediate', 'standing, twist, balancing', 'https://www.dropbox.com/s/o2cb4qluwqkikqw/%20Parivrtta%20Utkata%20Konasana.jpg?dl=0', 'https://www.youtube.com/embed/hgKwnJW9ysw'),
('Eight-angle pose','' , 'Astavakrasana', 'Strengthens the wrists, arms and shoulders, tones the abdominals and the inner thighs', 'intermediate', 'arm balancing', 'https://www.dropbox.com/s/837ptf3s1v4nlv7/8angle-pose.jpg?dl=0', 'https://www.youtube.com/embed/QDfqM33mVlg'),
('Archer pose', '', 'Akarna Dhanurasana','Increases hip mobility, strengthens arms and shoulders, stretches arms and legs,improves core strength.', 'intermediate', 'seated', 'https://www.dropbox.com/s/mk43548zzgz4bqj/archer.jpg?dl=0', 'https://www.youtube.com/embed/peh9uHiRGrQ'),
('Half frog', '', 'Ardha Bhekasana', 'Strengthens the back muscles, and opens up the abdominals, and the entire front line of the body, stretches the hips, ankles, shoulders, and front of the legs. It increases flexibility in the back muscles, and mobility in the spine, decreases the risk of knee injuries due to the stretching and strengthening of the muscles surrounding the knees. This backbend opens up the front of the body, is highly energizing, as it stimulates the respiratory and digestive system by compressing the intestines slightly. Eases menstrual cramps and menopausal symptoms.', 'intermediate', 'backbend', 'https://www.dropbox.com/s/zbugh6renwh0uq3/ardha%20bekhasana.jpg?dl=0', 'https://www.youtube.com/embed/K2QimPsO8zw'),
('Child pose', '', 'Balasana', 'Resting pose, counter asana for various asanas, stretches the hips, thighs, and ankles while reducing stress and fatigue. It gently relaxes the muscles on the front of the body while softly and passively stretching the muscles of the back torso.', 'beginner', 'forward bend, restorative', 'https://www.dropbox.com/s/i09dsh65po6s2hz/child.png?dl=0', 'https://www.youtube.com/embed/V22xxybieHk'),
('Crow', '', 'Bakasana', 'Tones the abdominal wall, strengthens abdominal organs to aide in lower back pain and indigestion,
strengthens arms, stretches and strengthens the back, and inner thighs, opens the groin, strengthens the wrists and builds endurance and focus', 'intermediate', 'arm balance', 'https://www.dropbox.com/s/e14lxb37c8zbd9v/crow.jpg?dl=0', 'https://www.youtube.com/embed/tmTrSGBvaoE'),
('King dancer pose', 'Dancer', 'Natarajasana', 'Builds full-body strength, flexibility, and coordination. It opens the shoulders, chest, and hips, as it stretches and strengthens the thighs, ankles, and abdomen, develops greater flexibility in spine, shoulders, and hamstrings.', 'intermediate', 'standing, balancing, heart openner', 'https://www.dropbox.com/s/0snr003fppb0qyd/dancer.jpg?dl=0', 'https://www.youtube.com/embed/3hT2H0mMHNQ'),
('Downward facing dog', 'Down dog', 'Adho Mukha Svanasana', 'Stretches hips, hamstrings, and calves, strengthens your ankles, quadriceps, and shoulders, tones abdominal muscles, decompresses the spinal column and removes fatigue', 'begginer', 'Forward Bend, Inversion, Resting', 'https://www.dropbox.com/s/401ub4acendpbje/down%20dog.png?dl=0', 'https://www.youtube.com/embed/YqOqM79McYY'),
('Forward Fold','', 'Paschimottanasana', 'Calms the brain and helps relieve stress and mild depression, Stretches the spine, shoulders, hamstrings, stimulates the liver, kidneys, ovaries, and uterus, improves digestion, helps relieve the symptoms of menopause and menstrual discomfort, soothes headache, anxiety and reduces fatigue.', 'beginner', 'Forward bend, Seated', 'https://www.dropbox.com/s/ovsy4yq1lfa3cpc/forward%20fold%20sit.png?dl=0', 'https://www.youtube.com/embed/Xn1wigQSrmI'),
('Cow face pose', '', 'Gomukhasana', 'Stretches your hips, thighs, ankles and chest, shoulders, anterior deltoids, triceps, inner armpits and lats', 'intermediate', 'seated, forward bend', 'https://www.dropbox.com/s/lq513uypfk5af0a/gomukasana.png?dl=0', 'https://www.youtube.com/embed/RApbaPSOCno'),
('Half monkey', '', 'Ardha Hanumanasana', 'Stretches the thighs, hamstrings, and groins, and is great prep work for the full expression of the splits.', 'beginner', 'hip openner, seated, forward bend', 'https://www.dropbox.com/s/f5ikayctrfxz1fs/half%20monkey.png?dl=0', 'https://www.youtube.com/embed/H_GIJXDYcww'),
('Handstand', '', '', 'Strengthening upper body, relieves stress, increases focus, improves blood flow, increases grip gtrength, strengthens shoulders and arms.', 'intermediate', 'inversion, hand balancing', 'https://www.dropbox.com/s/liq5f2il7iih30s/handstand.png?dl=0', 'https://www.youtube.com/embed/YelQIEhc5fg'),
('Monkey king pose','Split with backbend', 'Hanumanasana wwith backbend', 'intense hip openner, stretches the thighs, hamstrings, and groins, opens chest and armpits, front and back body', 'advanced', 'seated heart opener', 'https://www.dropbox.com/s/ighn09390sfvxun/Hanumanasana%20with%20backbend.jpg?dl=0', 'https://www.youtube.com/embed/_-J1hR2j9g8'),
('Garland pose', 'Yogi squat', 'Malasana', 'Stretches the thighs, groin, hips, ankles, and torso. It tones the abdominal muscles and improves the function of the colon to help with elimination. Increases circulation and blood flow in the pelvis, which can help regulate sexual energy.', 'beginner', 'standing, hip opener', 'https://www.dropbox.com/s/1hoxq1r8tkkf1yf/malasana.png?dl=0', 'https://www.youtube.com/embed/GLf_oVOYbSU' );
COMMIT;     
       
       
       
       
      




